version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: taskflow-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow
    volumes:
      - taskflow_pgdata:/var/lib/postgresql/data

volumes:
  taskflow_pgdata:
